# Generated by Django 5.2.4 on 2026-04-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomVirtualTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gltf_file', models.FileField(help_text='GLB/GLTF model for Three.js', upload_to='room_twins/gltf/')),
                ('background_audio', models.FileField(blank=True, help_text='Optional ambient loop (mp3, ogg, wav)', upload_to='room_twins/audio/')),
                ('climate_data', models.JSONField(blank=True, default=dict, help_text='e.g. {"temperature_c": 22, "scent": "Jasmine"}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_twin', to='rooms.room')),
            ],
            options={
                'verbose_name': 'room virtual twin',
                'verbose_name_plural': 'room virtual twins',
            },
        ),
    ]
