# Generated by Django 5.2.4 on 2026-04-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_virtual_twin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomvirtualtwin',
            name='background_audio',
        ),
        migrations.RemoveField(
            model_name='roomvirtualtwin',
            name='gltf_file',
        ),
        migrations.AddField(
            model_name='roomvirtualtwin',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Optional HTTPS link to ambient audio (mp3, ogg, wav).', max_length=500),
        ),
        migrations.AddField(
            model_name='roomvirtualtwin',
            name='model_url',
            field=models.URLField(blank=True, help_text='HTTPS link to a .glb or .gltf file. Leave blank to use the default showcase model (https://modelviewer.dev/shared-assets/models/Astronaut.glb).', max_length=500),
        ),
    ]
