# Generated by Django 5.2.4 on 2026-04-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_virtual_twin_url_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomvirtualtwin',
            name='model_url',
            field=models.URLField(blank=True, help_text='Required for a unique 3D preview: paste a full HTTPS URL to this room’s .glb or .gltf file. Each room’s virtual twin should use a different URL. If empty, the site-wide fallback URL from environment (VIRTUAL_ROOM_FALLBACK_MODEL_URL) is used when configured.', max_length=500),
        ),
    ]
