# Generated by Django 5.2.4 on 2026-04-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_virtual_twin_model_url_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomvirtualtwin',
            name='model_url',
            field=models.URLField(blank=True, help_text='HTTPS URL for this room’s 3D preview: a Sketchfab model or embed link (sketchfab.com), or a direct link to a .glb / .gltf file. If empty, VIRTUAL_ROOM_FALLBACK_MODEL_URL (environment) is used when set.', max_length=500),
        ),
    ]
